package report

import (
	"bufio"
	"fmt"
	"io"
	"strings"

	"github.com/6-SlX-6/stacksentry/internal/findings"
)

var severityHeadings = map[findings.Severity]string{
	findings.SeverityCritical: "Critical",
	findings.SeverityHigh:     "High",
	findings.SeverityMedium:   "Medium",
	findings.SeverityLow:      "Low",
	findings.SeverityInfo:     "Info",
}

// RenderMarkdown writes a self-contained Markdown report suitable for
// issues, change requests and audit documentation.
func RenderMarkdown(w io.Writer, r *Report) error {
	bw := bufio.NewWriter(w)
	p := func(format string, args ...any) { fmt.Fprintf(bw, format, args...) }

	p("# StackSentry Scan Report\n\n")

	p("## Scan Summary\n\n")
	p("| Property | Value |\n|---|---|\n")
	p("| Scanner | StackSentry v%s |\n", cell(r.Scanner.Version))
	p("| Scan type | %s |\n", scanTypeLabel(r.Scan.Type))
	p("| Scan time | %s |\n", r.Scan.StartedAt.Format("2006-01-02T15:04:05Z"))
	p("| Rules evaluated | %d of %d |\n", r.Scan.RulesEvaluated, r.Scan.RulesTotal)
	p("| Findings | %d |\n", r.Summary.Total)
	p("| Minimum severity shown | %s |\n", r.Scan.Options.MinSeverity)
	if r.Summary.FailOn != nil {
		p("| Fail-on threshold | %s |\n", r.Summary.FailOn)
		p("| Result | **%s** (%d at or above threshold) |\n", strings.ToUpper(r.Summary.Result), r.Summary.AtOrAboveFailOn)
	} else {
		p("| Fail-on threshold | not set |\n")
	}
	p("\n")

	p("## Target\n\n")
	p("| Property | Value |\n|---|---|\n")
	switch {
	case r.Target.Compose != nil:
		c := r.Target.Compose
		p("| Compose files | %s |\n", codeList(c.Files))
		p("| Project | %s |\n", code(c.ProjectName))
		p("| Services analyzed | %d |\n", c.ServiceCount)
		p("| Services | %s |\n", codeList(c.Services))
	case r.Target.Host != nil:
		h := r.Target.Host
		p("| Docker endpoint | %s |\n", code(h.Endpoint))
		p("| Docker version | %s |\n", cell(h.ServerVersion))
		p("| API version | %s |\n", cell(h.APIVersion))
		p("| Operating system | %s |\n", cell(strings.TrimSpace(h.OperatingSystem+" ("+h.OSType+"/"+h.Architecture+")")))
		p("| Containers analyzed | %d (%d running) |\n", h.ContainersTotal, h.ContainersRunning)
		p("| Images | %d |\n", h.Images)
	default:
		p("| Name | %s |\n", cell(r.Target.Name))
	}
	p("\n")

	p("## Finding Statistics\n\n")
	shown := findings.Count(r.Findings)
	p("| Severity | Found | Shown in this report |\n|---|---:|---:|\n")
	for _, sev := range findings.AllSeverities() {
		p("| %s | %d | %d |\n", severityHeadings[sev], r.Summary.BySeverity.Get(sev), shown.Get(sev))
	}
	p("| **Total** | **%d** | **%d** |\n\n", r.Summary.Total, r.Summary.Displayed)
	if r.Summary.Suppressed > 0 {
		p("%s suppressed by documented `x-stacksentry` exceptions (not included above).\n\n",
			plural(r.Summary.Suppressed, "finding was", "findings were"))
	}

	p("## Findings by Severity\n\n")
	if len(r.Findings) == 0 {
		p("No findings to report.\n\n")
	}
	index := 0
	for _, sev := range findings.AllSeverities() {
		group := bySeverity(r.Findings, sev)
		if len(group) == 0 {
			continue
		}
		p("### %s (%d)\n\n", severityHeadings[sev], len(group))
		p("| # | Rule | Target | Finding |\n|---:|---|---|---|\n")
		for _, f := range group {
			index++
			p("| %d | %s | %s | %s |\n", index, f.RuleID, code(f.TargetName), cell(f.Title))
		}
		p("\n")
	}

	p("## Detailed Findings\n\n")
	if len(r.Findings) == 0 {
		p("No findings to report.\n\n")
	}
	for i, f := range r.Findings {
		p("### %d. %s: %s\n\n", i+1, f.RuleID, text(f.Title))
		p("- **Rule ID:** %s (version %s)\n", f.RuleID, text(f.RuleVersion))
		p("- **Severity:** %s\n", f.Severity)
		p("- **Category:** %s\n", f.Category)
		p("- **Confidence:** %s\n", f.Confidence)
		target := fmt.Sprintf("%s %s", f.TargetType, code(f.TargetName))
		if loc := f.Location.String(); loc != "" {
			target += " (" + code(loc) + ")"
		}
		p("- **Affected target:** %s\n", target)
		p("- **Documentation:** <%s>\n\n", f.Documentation)
		p("**Description:** %s\n\n", text(f.Description))
		if len(f.Evidence) > 0 {
			p("**Evidence:**\n\n%s\n", codeBlock(f.Evidence))
		}
		p("**Why it matters:** %s\n\n", text(f.WhyItMatters))
		p("**Recommended remediation:** %s\n\n", text(f.Remediation))
	}

	p("## Scan Limitations\n\n")
	for _, n := range notes(r) {
		p("- %s\n", text(n))
	}
	for _, s := range r.Suppressed {
		p("- Suppressed %s for %s: %s\n", s.RuleID, code(s.TargetName), text(s.SuppressionReason))
	}
	p("- %s\n\n", text(staticDisclaimer(r.Scan.Type)))

	p("## Remediation Priorities\n\n")
	writePriorities(bw, r.Findings)

	p("## Generated By\n\n")
	p("Generated by StackSentry v%s on %s. StackSentry performs local, deterministic, rule-based analysis; "+
		"no data left the machine that ran the scan. Findings support, but do not replace, a complete security review.\n",
		text(r.Scanner.Version), r.Scan.StartedAt.Format("2006-01-02T15:04:05Z"))
	return bw.Flush()
}

func scanTypeLabel(t ScanType) string {
	switch t {
	case ScanCompose:
		return "Docker Compose (static analysis)"
	case ScanHost:
		return "Docker host (local daemon inspection)"
	default:
		return string(t)
	}
}

func staticDisclaimer(t ScanType) string {
	if t == ScanHost {
		return "Host scans read the Docker API and local configuration without changing anything. Settings that are " +
			"not exposed by the API, or that need more privileges, are listed above when they could not be inspected."
	}
	return "Static analysis sees only the Compose files. Image contents (USER, HEALTHCHECK), daemon-wide settings " +
		"such as daemon.json log rotation, and values injected at deploy time are not visible to this scan."
}

func bySeverity(list []findings.Finding, sev findings.Severity) []findings.Finding {
	var out []findings.Finding
	for _, f := range list {
		if f.Severity == sev {
			out = append(out, f)
		}
	}
	return out
}

var priorityLabels = []struct {
	severities []findings.Severity
	label      string
}{
	{[]findings.Severity{findings.SeverityCritical}, "Fix before deploying (critical)"},
	{[]findings.Severity{findings.SeverityHigh}, "Fix soon (high)"},
	{[]findings.Severity{findings.SeverityMedium}, "Plan a fix (medium)"},
	{[]findings.Severity{findings.SeverityLow, findings.SeverityInfo}, "Hardening backlog (low and info)"},
}

// writePriorities groups findings by severity bucket and rule so that one
// remediation can be applied to all affected targets at once.
func writePriorities(w io.Writer, list []findings.Finding) {
	if len(list) == 0 {
		fmt.Fprint(w, "Nothing to remediate at the selected severity.\n\n")
		return
	}
	step := 0
	for _, bucket := range priorityLabels {
		type ruleGroup struct {
			title   string
			targets []string
		}
		var order []string
		groups := map[string]*ruleGroup{}
		for _, f := range list {
			if !severityIn(f.Severity, bucket.severities) {
				continue
			}
			g, ok := groups[f.RuleID]
			if !ok {
				g = &ruleGroup{title: f.Title}
				groups[f.RuleID] = g
				order = append(order, f.RuleID)
			}
			if !contains(g.targets, f.TargetName) {
				g.targets = append(g.targets, f.TargetName)
			}
		}
		if len(order) == 0 {
			continue
		}
		step++
		fmt.Fprintf(w, "%d. **%s**\n", step, bucket.label)
		for _, id := range order {
			g := groups[id]
			fmt.Fprintf(w, "   - %s %s: %s\n", id, text(g.title), codeList(g.targets))
		}
	}
	fmt.Fprintln(w)
}

func severityIn(sev findings.Severity, list []findings.Severity) bool {
	for _, s := range list {
		if s == sev {
			return true
		}
	}
	return false
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

var markdownEscaper = strings.NewReplacer(
	`\`, `\\`, "`", "\\`", "*", `\*`, "_", `\_`, "[", `\[`, "]", `\]`,
	"<", `\<`, ">", `\>`, "|", `\|`, "#", `\#`, "\n", " ",
)

// EscapeMarkdown escapes characters that Markdown would interpret, so that
// free text renders literally.
func EscapeMarkdown(s string) string { return markdownEscaper.Replace(s) }

func text(s string) string { return EscapeMarkdown(s) }

// cell escapes text for use inside a table cell.
func cell(s string) string { return text(s) }

// code renders s as inline code, choosing a delimiter that is safe for the
// content and keeping table cells intact.
func code(s string) string {
	if s == "" {
		return "—"
	}
	s = strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "|", `\|`)
	fence := "`"
	for strings.Contains(s, fence) {
		fence += "`"
	}
	if strings.HasPrefix(s, "`") || strings.HasSuffix(s, "`") {
		return fence + " " + s + " " + fence
	}
	return fence + s + fence
}

func codeList(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = code(it)
	}
	return strings.Join(parts, ", ")
}

// codeBlock renders lines in a fenced block whose fence cannot be closed by
// the content.
func codeBlock(lines []string) string {
	body := strings.Join(lines, "\n")
	fence := "```"
	for strings.Contains(body, fence) {
		fence += "`"
	}
	return fence + "text\n" + body + "\n" + fence + "\n"
}
