package cli

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var updateDocs = flag.Bool("update", false, "rewrite the generated part of docs/rules.md")

const (
	beginMarker = "<!-- BEGIN GENERATED RULES: run `make docs` to update -->\n"
	endMarker   = "<!-- END GENERATED RULES -->\n"
)

// TestRulesDocUpToDate keeps docs/rules.md in sync with the rule metadata
// compiled into the binary.
func TestRulesDocUpToDate(t *testing.T) {
	path := filepath.Join("..", "..", "docs", "rules.md")
	doc, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := strings.ReplaceAll(string(doc), "\r\n", "\n")
	start := strings.Index(text, beginMarker)
	end := strings.Index(text, endMarker)
	if start < 0 || end < start {
		t.Fatalf("%s must contain the generated-section markers", path)
	}
	var generated bytes.Buffer
	if err := writeRulesReference(&generated); err != nil {
		t.Fatal(err)
	}
	current := text[start+len(beginMarker) : end]
	want := "\n" + generated.String() + "\n"
	if current == want {
		return
	}
	if !*updateDocs {
		t.Fatalf("%s is out of date; run `make docs`", path)
	}
	updated := text[:start+len(beginMarker)] + want + text[end:]
	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		t.Fatal(err)
	}
}
