package cli

import (
	"bytes"
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var updateDocs = flag.Bool("update", false, "rewrite the generated parts of docs/rules.md and README.md")

// TestRulesDocUpToDate keeps docs/rules.md in sync with the rule metadata
// compiled into the binary.
func TestRulesDocUpToDate(t *testing.T) {
	checkGeneratedSection(t, filepath.Join("..", "..", "docs", "rules.md"),
		"<!-- BEGIN GENERATED RULES: run `make docs` to update -->\n",
		"<!-- END GENERATED RULES -->\n", writeRulesReference)
}

// TestReadmeRuleTablesUpToDate keeps the rule overview in README.md in sync.
func TestReadmeRuleTablesUpToDate(t *testing.T) {
	checkGeneratedSection(t, filepath.Join("..", "..", "README.md"),
		"<!-- BEGIN GENERATED RULE TABLES: run `make docs` to update -->\n",
		"<!-- END GENERATED RULE TABLES -->\n", writeReadmeRuleTables)
}

func checkGeneratedSection(t *testing.T, path, begin, end string, generate func(io.Writer) error) {
	t.Helper()
	doc, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	text := strings.ReplaceAll(string(doc), "\r\n", "\n")
	start := strings.Index(text, begin)
	stop := strings.Index(text, end)
	if start < 0 || stop < start {
		t.Fatalf("%s must contain the generated-section markers", path)
	}
	var generated bytes.Buffer
	if err := generate(&generated); err != nil {
		t.Fatal(err)
	}
	current := text[start+len(begin) : stop]
	want := "\n" + generated.String() + "\n"
	if current == want {
		return
	}
	if !*updateDocs {
		t.Fatalf("%s is out of date; run `make docs`", path)
	}
	updated := text[:start+len(begin)] + want + text[stop:]
	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		t.Fatal(err)
	}
}
